service: music-service

provider:
  name: aws
  runtime: nodejs6.10
  timeout: 30
  deploymentBucket: music-repository-serverless-deploy
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        Fn::Join:
          - '/'
          - - Fn::Join:
              - ':'
              - - arn:aws:dynamodb
                - Ref: AWS::Region
                - Ref: AWS::AccountId
                - table
            - Ref: MusicTable

functions:
  music:
    handler: handler.musicHandler
    environment:
      TABLE_NAME:
        Ref: MusicTable
    events:
      - http:
          path: music
          method: get
          cors: true
      - http:
          path: music
          method: post
          cors: true

resources:
  Resources:

    MusicTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: uid
            AttributeType: S
          - AttributeName: owner
            AttributeType: S
        KeySchema:
          - AttributeName: uid
            KeyType: HASH
          - AttributeName: owner
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5